-- --------------------------------------------- --
-- Crear base de datos
CREATE DATABASE INCOLAB;


-- Para utilizar la base de datos incolab
USE INCOLAB;

-- Creación de tablas
-- --------------------------------------------
-- Responsables del inventario
CREATE TABLE RESPONSABLES (
	ID_RESPONSABLE CHAR(6) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(60),
	TELEFONO VARCHAR(12),
	CORREO VARCHAR(60),
	ESTADO INT(1)
);
-- --------------------------------------------
CREATE TABLE USUARIOS(
	ID_RESPONSABLE CHAR (6) NOT NULL,
	NOMBRE_USUARIO VARCHAR(30),
	CONTRASENNA VARCHAR(10),
	FECHA  DATETIME,
	ESTADO INT(1),
	ROL VARCHAR(3)
);
-- --------------------------------------------
CREATE TABLE PROVEEDORES(
	ID_PROVEEDOR CHAR(7) NOT NULL PRIMARY KEY,
	NOMBRE_PROVEEDOR VARCHAR(60),
	DESCRIPCION VARCHAR(100),
	TELEFONO VARCHAR(12),
	CORREO VARCHAR(60),
	ESTADO INT(1)
);
-- --------------------------------------------
-- Categorias principales para los productos (ej: toma muestras)
CREATE TABLE CATEGORIAS(
	COD_CATEGORIA CHAR(7) NOT NULL PRIMARY KEY,
	NOMBRE_CATEGORIA VARCHAR(100)
);
-- --------------------------------------------
-- SubCategprias para los productos (ej: consumible)
CREATE TABLE SUBCATEGORIAS(
	COD_SUB_CATEGORIA CHAR(7) NOT NULL PRIMARY KEY,
	NOMBRE_SUB_CATEGORIA VARCHAR(100)
);
-- --------------------------------------------
-- Unidades de presentacion para los productos (ej: botella, UND)
CREATE TABLE UNIDADES_PRESENTACION(
  ID_UNIDADES_PRESENTACION INT auto_increment NOT NULL PRIMARY KEY,
	NOMBRE_UNIDAD VARCHAR(30)
);
-- --------------------------------------------- --
-- Presentacion
CREATE TABLE PRESENTACION(
  ID_PRESENTACION INT auto_increment NOT NULL PRIMARY KEY,
  NOMBRE_PRESENTACION VARCHAR(30)
);
-- --------------------------------------------- --
-- Presentacion de cada producto
CREATE TABLE PRESENTACIONES(
	COD_PRODUCTO CHAR(7) NOT NULL,
	ID_PRESENTACION INT,
	ID_UNIDADES_PRESENTACION INT,
	UNIDADES INT(11)
);
-- --------------------------------------------- --
CREATE TABLE PRODUCTOS(
	COD_PRODUCTO CHAR (7) NOT NULL PRIMARY KEY,
	NOMBRE_PRODUCTO VARCHAR (120),
	COD_CATEGORIA CHAR(7) NOT NULL,
	COD_SUB_CATEGORIA CHAR(7) NOT NULL,
	COSTO_TOTAL_PRODUCTO FLOAT,
	COSTO_UNITARIO FLOAT,
	FECHA_VENCIMIENTO DATE,
	ID_PROVEEDOR CHAR(7) NOT NULL,
	CANTIDAD_STOCK INT(4),
	CANTIDAD_USO INT(4),
	TOTAL_UNITARIO INT(11),
	ESTADO_CRITICO INT(11),
	ESTADO INT(1),
	DESCRIPCION VARCHAR(150),
	MONEDA VARCHAR(2),
  TOTAL_INICIAL INT(11)
);
-- --------------------------------------------- --
CREATE TABLE SUCURSALES(
	ID_SUCURSAL CHAR(6) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(30),
	DIRECCION VARCHAR(150),
	TELEFONO VARCHAR(12),
	ESTADO INT(1)
);
-- --------------------------------------------- --
-- Para entradas y salidas de productos
CREATE TABLE TIPO_ORDEN(
	ID_ORDEN INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DESCRIPCION VARCHAR(150)
);
-- --------------------------------------------- --
CREATE TABLE ENCABEZADO(
	ID_ENCABEZADO INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	FECHA DATETIME,
	ID_ORDEN INT(11) NOT NULL
);
-- --------------------------------------------- --
CREATE TABLE DETALLES(
	ID_ENCABEZADO INT(11) NOT NULL,
	ID_RESPONSABLE CHAR(6) NOT NULL,
	TIPO VARCHAR(30), -- si es una entrada o una salida
	SUCURSAL_ORIGEN VARCHAR(50),
	SUCURSAL_DESTINO VARCHAR(50),
	COD_PRODUCTO CHAR(7),
	DESCRIPCION VARCHAR(120),
	CANTIDAD_SALIDA  INT(11),
	CANTIDAD_ENTRADA INT(11)
);

create table reportes (
	cod_producto char(7),
    precio int,
		precio_unitario int,
    uso int,
    fecha date
);

-- ---------------------------------------------------------------- --
-- ---------------------------------------------------------------- --
-- NOTAS:
-- Las tablas de sucursales, proveedores, categorias
-- subcategorias y responsables
-- debe estar llenas antes.
-- ---------------------------------------------------------------- --
-- ---------------------------------------------------------------- --
-- Creación de relaciones
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USU_RESP
FOREIGN KEY (ID_RESPONSABLE) REFERENCES RESPONSABLES(ID_RESPONSABLE);

ALTER TABLE ENCABEZADO ADD CONSTRAINT FK_ENC_TIP
FOREIGN KEY (ID_ORDEN) REFERENCES TIPO_ORDEN(ID_ORDEN);

ALTER TABLE DETALLES ADD CONSTRAINT FK_DET_PRO
FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTOS(COD_PRODUCTO);

ALTER TABLE DETALLES ADD CONSTRAINT FK_DET_RES
FOREIGN KEY (ID_RESPONSABLE) REFERENCES RESPONSABLES(ID_RESPONSABLE);

ALTER TABLE DETALLES ADD CONSTRAINT FK_DET_ENC
FOREIGN KEY (ID_ENCABEZADO) REFERENCES ENCABEZADO(ID_ENCABEZADO);

ALTER TABLE DETALLES ADD CONSTRAINT FK_DET_SUR_OR
FOREIGN KEY (SUCURSAL_ORIGEN) REFERENCES SUCURSALES(ID_SUCURSAL);

ALTER TABLE DETALLES ADD CONSTRAINT FK_DET_SUR_DE
FOREIGN KEY (SUCURSAL_DESTINO) REFERENCES SUCURSALES(ID_SUCURSAL);

ALTER TABLE  PRODUCTOS ADD CONSTRAINT FK_PROD_PROV
FOREIGN KEY (ID_PROVEEDOR ) REFERENCES PROVEEDORES(ID_PROVEEDOR);

ALTER TABLE  PRODUCTOS ADD CONSTRAINT FK_PROD_CATE
FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIAS(COD_CATEGORIA);

ALTER TABLE  PRODUCTOS ADD CONSTRAINT FK_PRO_SCA
FOREIGN KEY (COD_SUB_CATEGORIA) REFERENCES SUBCATEGORIAS(COD_SUB_CATEGORIA);

ALTER TABLE  PRESENTACIONES ADD CONSTRAINT FK_PRE_PRO
FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTOS(COD_PRODUCTO);

ALTER TABLE  PRESENTACIONES ADD CONSTRAINT FK_PRE_PRES
FOREIGN KEY (ID_PRESENTACION) REFERENCES PRESENTACION(ID_PRESENTACION);

ALTER TABLE  PRESENTACIONES ADD CONSTRAINT FK_PRE_UNID
FOREIGN KEY (ID_UNIDADES_PRESENTACION) REFERENCES UNIDADES_PRESENTACION(ID_UNIDADES_PRESENTACION);


ALTER TABLE reportes ADD CONSTRAINT FK_REP_PRO
FOREIGN KEY (cod_producto) REFERENCES productos(cod_producto);
-- ---------------------------------------------------------------- --
