INSERT INTO RESPONSABLES(ID_RESPONSABLE,NOMBRE,TELEFONO,CORREO,ESTADO) VALUES ('RES-01','LUIS DIEGO ALFARO','+50685241685','luisdiego@gmail.com',1);
INSERT INTO RESPONSABLES(ID_RESPONSABLE,NOMBRE,TELEFONO,CORREO,ESTADO) VALUES ('RES-02','ELIZABETH ORTEGA','+50670568941','elizabethor@gmail.com',1);
INSERT INTO RESPONSABLES(ID_RESPONSABLE,NOMBRE,TELEFONO,CORREO,ESTADO) VALUES ('RES-03','DIANA CABEZAS','+50682654766','dianacab@gmail.com',1);
INSERT INTO RESPONSABLES(ID_RESPONSABLE,NOMBRE,TELEFONO,CORREO,ESTADO) VALUES ('RES-04','ALBERTO GONZALEZ','+50685242245','albertg@gmail.com',1);
-- ---------------------------------------------------------------- --
INSERT INTO SUCURSALES(ID_SUCURSAL,NOMBRE,DIRECCION,TELEFONO,ESTADO) VALUES ('SUC-01','ALAJUELA CENTRO','ALAJUELA CENTRO, ALAJUELA','+50624307772',1);
INSERT INTO SUCURSALES(ID_SUCURSAL,NOMBRE,DIRECCION,TELEFONO,ESTADO) VALUES ('SUC-02','EL COYOL','COYOL, ALAJUELA','+50624337774',1);
INSERT INTO SUCURSALES(ID_SUCURSAL,NOMBRE,DIRECCION,TELEFONO,ESTADO) VALUES ('SUC-03','LA GUACIMA','LA GUACIMA, ALAJUELA','+50624390095',1);
INSERT INTO SUCURSALES(ID_SUCURSAL,NOMBRE,DIRECCION,TELEFONO,ESTADO) VALUES ('SUC-04','DESAMPARADOS','DESAMPARADOS, ALAJUELA','+50621016092',1);
INSERT INTO SUCURSALES(ID_SUCURSAL,NOMBRE,DIRECCION,TELEFONO,ESTADO) VALUES ('SUC-05','SAN RAFAEL','SAN RAFAEL, ALAJUELA','+50624382727',1);
INSERT INTO SUCURSALES(ID_SUCURSAL,NOMBRE,DIRECCION,TELEFONO,ESTADO) VALUES ('SUC-06','GRECIA','GRACIA, ALAJUELA','+50624442827',1);
-- -- ---------------------------------------------------------------- --
INSERT INTO PROVEEDORES(ID_PROVEEDOR,NOMBRE_PROVEEDOR,DESCRIPCION,TELEFONO, CORREO,ESTADO) VALUES ('PRO-01','JACKS','esta es una descripcion','+50688888888','prov1@gmail.com',1);
INSERT INTO PROVEEDORES(ID_PROVEEDOR,NOMBRE_PROVEEDOR,DESCRIPCION,TELEFONO, CORREO,ESTADO) VALUES ('PRO-02','POZUELO','esta es una descripcion','+50688888888','prov2@gmail.com',1);
INSERT INTO PROVEEDORES(ID_PROVEEDOR,NOMBRE_PROVEEDOR,DESCRIPCION,TELEFONO, CORREO,ESTADO) VALUES ('PRO-03','PIPASA','esta es una descripcion','+50688888888','prov3@gmail.com',1);
INSERT INTO PROVEEDORES(ID_PROVEEDOR,NOMBRE_PROVEEDOR,DESCRIPCION,TELEFONO, CORREO,ESTADO) VALUES ('PRO-04','FLORIDA BEBIDAS','esta es una descripcion','+50688888888','prov4@gmail.com',1);
INSERT INTO PROVEEDORES(ID_PROVEEDOR,NOMBRE_PROVEEDOR,DESCRIPCION,TELEFONO, CORREO,ESTADO) VALUES ('PRO-05','KOLBI','esta es una descripcion','+50688888888','prov5@gmail.com',1);
-- ---------------------------------------------------------------- --
INSERT INTO CATEGORIAS(COD_CATEGORIA, NOMBRE_CATEGORIA) VALUES ('TMT-00','TOMA MUESTRA');
INSERT INTO CATEGORIAS(COD_CATEGORIA, NOMBRE_CATEGORIA) VALUES ('IPV-00','INMUNOLOGIA - PRUEBAS RAPIDAS');
INSERT INTO CATEGORIAS(COD_CATEGORIA, NOMBRE_CATEGORIA) VALUES ('IHM-00','INMUNOHEMATOLOGIA');
INSERT INTO CATEGORIAS(COD_CATEGORIA, NOMBRE_CATEGORIA) VALUES ('BMC-00','BACTERIOLOGIA - MEDIOS DE CULTIVO BOTELLAS');
INSERT INTO CATEGORIAS(COD_CATEGORIA, NOMBRE_CATEGORIA) VALUES ('TCN-00','TINCIONES');
-- ---------------------------------------------------------------- --
INSERT INTO SUBCATEGORIAS(COD_SUB_CATEGORIA, NOMBRE_SUB_CATEGORIA) VALUES ('CON-00','CONSUMIBLE');
INSERT INTO SUBCATEGORIAS(COD_SUB_CATEGORIA, NOMBRE_SUB_CATEGORIA) VALUES ('CRI-00','CRISTALERIA');
INSERT INTO SUBCATEGORIAS(COD_SUB_CATEGORIA, NOMBRE_SUB_CATEGORIA) VALUES ('REA-00','REACTIVO');
INSERT INTO SUBCATEGORIAS(COD_SUB_CATEGORIA, NOMBRE_SUB_CATEGORIA) VALUES ('PRU-00','PRUEBA');
INSERT INTO SUBCATEGORIAS(COD_SUB_CATEGORIA, NOMBRE_SUB_CATEGORIA) VALUES ('INS-00','INSUMO');
INSERT INTO SUBCATEGORIAS(COD_SUB_CATEGORIA, NOMBRE_SUB_CATEGORIA) VALUES ('MCU-00','MEDIO CULTIVO');
INSERT INTO SUBCATEGORIAS(COD_SUB_CATEGORIA, NOMBRE_SUB_CATEGORIA) VALUES ('COT-00','CONTROL');
INSERT INTO SUBCATEGORIAS(COD_SUB_CATEGORIA, NOMBRE_SUB_CATEGORIA) VALUES ('TIN-00','TINCION');
INSERT INTO SUBCATEGORIAS(COD_SUB_CATEGORIA, NOMBRE_SUB_CATEGORIA) VALUES ('CAL-00','CALIBRADOR');
INSERT INTO SUBCATEGORIAS(COD_SUB_CATEGORIA, NOMBRE_SUB_CATEGORIA) VALUES ('CBA-00','CEPA BACT');
-- ---------------------------------------------------------------- --
INSERT INTO UNIDADES_PRESENTACION(NOMBRE_UNIDAD) VALUES ('PAQUETE');
INSERT INTO UNIDADES_PRESENTACION(NOMBRE_UNIDAD) VALUES ('GALON');
INSERT INTO UNIDADES_PRESENTACION(NOMBRE_UNIDAD) VALUES ('BOTELLA');
INSERT INTO UNIDADES_PRESENTACION(NOMBRE_UNIDAD) VALUES ('PRUEBAS');
INSERT INTO UNIDADES_PRESENTACION(NOMBRE_UNIDAD) VALUES ('UND');
INSERT INTO UNIDADES_PRESENTACION(NOMBRE_UNIDAD) VALUES ('TUBOS');
INSERT INTO UNIDADES_PRESENTACION(NOMBRE_UNIDAD) VALUES ('JUEGOS');
INSERT INTO UNIDADES_PRESENTACION(NOMBRE_UNIDAD) VALUES ('SET');
INSERT INTO UNIDADES_PRESENTACION(NOMBRE_UNIDAD) VALUES ('VIAL');
INSERT INTO UNIDADES_PRESENTACION(NOMBRE_UNIDAD) VALUES ('PROBETA');
-- ---------------------------------------------------------------- --
INSERT INTO PRESENTACION(NOMBRE_PRESENTACION) VALUES ('PAQUETE 500g');
INSERT INTO PRESENTACION(NOMBRE_PRESENTACION) VALUES ('CAJA');
INSERT INTO PRESENTACION(NOMBRE_PRESENTACION) VALUES ('RACK');
INSERT INTO PRESENTACION(NOMBRE_PRESENTACION) VALUES ('KIT');
INSERT INTO PRESENTACION(NOMBRE_PRESENTACION) VALUES ('GALON');
INSERT INTO PRESENTACION(NOMBRE_PRESENTACION) VALUES ('UND');
INSERT INTO PRESENTACION(NOMBRE_PRESENTACION) VALUES ('BOLSA');
INSERT INTO PRESENTACION(NOMBRE_PRESENTACION) VALUES ('JUEGO');
INSERT INTO PRESENTACION(NOMBRE_PRESENTACION) VALUES ('BOTELLA 950ml');
INSERT INTO PRESENTACION(NOMBRE_PRESENTACION) VALUES ('SET');
-- ---------------------------------------------------------------- --
-- usado para prueba de graficos
INSERT INTO HISTORIAL VALUES('TMT-21','ENERO 2019', 24);
INSERT INTO HISTORIAL VALUES('TMT-23','MARZO 2019', 120);
INSERT INTO HISTORIAL VALUES('TMT-21','ENERO 2018', 140);
INSERT INTO HISTORIAL VALUES('TMT-23','MARZO 2018', 99);
